FROM python:3.9.14-alpine3.16
MAINTAINER Stacy Olivas <kg7qin@arrl.net>

WORKDIR /usr/src/app

RUN apk update; \
    apk add bash curl

RUN mkdir /wheel
COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

VOLUME /usr/src/app/logs

ARG LOGSRV_HOSTIP
ENV LOGSRV_HOSTIP=$LOGSRV_HOSTIP
ARG LOGSRV_PORT
ENV LOGSRV_PORT=$LOGSRV_PORT
ARG LOGSRV_PREFIX
ENV LOGSRV_PREFIX=$LOGSRV_PREFIX
ARG LOGSRV_WEBHOST
ENV LOGSRV_WEBHOST=$LOGSRV_WEBHOST
ARG LOGSRV_WEBPORT
ENV LOGSRV_WEBPORT=$LOGSRV_WEBPORT
ARG LOGSRV_WEBSOCKURL
ENV LOGSRV_WEBSOCKURL=$LOGSRV_WEBSOCKURL
ARG LOGSRV_SSL
ENV LOGSRV_SSL=$LOGSRV_SSL
ARG LOGSRV_NEWLINE
ENV LOGSRV_NEWLINE=$LOGSRV_NEWLINE
ARG LOGSRV_TITLE
ENV LOGSRV_TITLE=$LOGSRV_TITLE

EXPOSE 8000
EXPOSE 8765

COPY *.pem ./
COPY *.py ./
COPY *.html ./

RUN chmod +x ./server.py

CMD [ "python3", "server.py" ]

